"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookEvents = void 0;
var WebhookEvents;
(function (WebhookEvents) {
    WebhookEvents[WebhookEvents["taskCreated"] = 0] = "taskCreated";
    WebhookEvents[WebhookEvents["taskUpdated"] = 1] = "taskUpdated";
    WebhookEvents[WebhookEvents["taskDeleted"] = 2] = "taskDeleted";
    WebhookEvents[WebhookEvents["taskPriorityUpdated"] = 3] = "taskPriorityUpdated";
    WebhookEvents[WebhookEvents["taskStatusUpdated"] = 4] = "taskStatusUpdated";
    WebhookEvents[WebhookEvents["taskAssigneeUpdated"] = 5] = "taskAssigneeUpdated";
    WebhookEvents[WebhookEvents["taskDueDateUpdated"] = 6] = "taskDueDateUpdated";
    WebhookEvents[WebhookEvents["taskTagUpdated"] = 7] = "taskTagUpdated";
    WebhookEvents[WebhookEvents["taskMoved"] = 8] = "taskMoved";
    WebhookEvents[WebhookEvents["taskCommentPosted"] = 9] = "taskCommentPosted";
    WebhookEvents[WebhookEvents["taskCommentUpdated"] = 10] = "taskCommentUpdated";
    WebhookEvents[WebhookEvents["taskTimeEstimateUpdated"] = 11] = "taskTimeEstimateUpdated";
    WebhookEvents[WebhookEvents["taskTimeTrackedUpdated"] = 12] = "taskTimeTrackedUpdated";
    WebhookEvents[WebhookEvents["listCreated"] = 13] = "listCreated";
    WebhookEvents[WebhookEvents["listUpdated"] = 14] = "listUpdated";
    WebhookEvents[WebhookEvents["listDeleted"] = 15] = "listDeleted";
    WebhookEvents[WebhookEvents["folderCreated"] = 16] = "folderCreated";
    WebhookEvents[WebhookEvents["folderUpdated"] = 17] = "folderUpdated";
    WebhookEvents[WebhookEvents["folderDeleted"] = 18] = "folderDeleted";
    WebhookEvents[WebhookEvents["spaceCreated"] = 19] = "spaceCreated";
    WebhookEvents[WebhookEvents["spaceUpdated"] = 20] = "spaceUpdated";
    WebhookEvents[WebhookEvents["spaceDeleted"] = 21] = "spaceDeleted";
    WebhookEvents[WebhookEvents["goalCreated"] = 22] = "goalCreated";
    WebhookEvents[WebhookEvents["goalUpdated"] = 23] = "goalUpdated";
    WebhookEvents[WebhookEvents["goalDeleted"] = 24] = "goalDeleted";
    WebhookEvents[WebhookEvents["keyResultCreated"] = 25] = "keyResultCreated";
    WebhookEvents[WebhookEvents["keyResultUpdated"] = 26] = "keyResultUpdated";
    WebhookEvents[WebhookEvents["keyResultDeleted"] = 27] = "keyResultDeleted";
})(WebhookEvents = exports.WebhookEvents || (exports.WebhookEvents = {}));
